## 기존 values.yaml 내용에 추가로 아래 항목들을 추가합니다.
replicaCount: 1
namespaceOverride: "test"
commonLabels:
  app: "nls-elastic"
containerPorts:
  amqp: 9200
service:
  type: NodePort
  nodePorts:
    amqp: 30085
imagePullSecrets: [regsecret]
