replicaCount: 1

image:
  repository: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-elasticsearch
  tag: "7.10.2"
  pullPolicy: Always

imagePullSecrets:
  - name: regsecret

service:
  type: NodePort
  port: 9200
  nodePort: 30082

resources:
  requests:
    cpu: 100m
    memory: 1200Mi

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
  startup:
    failureThreshold: 30
    periodSeconds: 10

elasticsearch:
  username: elastic
  password: elastic
