elasticsearch:
  replicaCount: 1
  image:
    repository: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-elasticsearch
    tag: "7.10.2"
    pullPolicy: Always
  imagePullSecrets:
    - name: regsecret
  service:
    type: NodePort
    port: 9200
    nodePort: 30083
  resources:
    requests:
      cpu: 100m
      memory: 1200Mi
  probes:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 30
      periodSeconds: 10
    startup:
      failureThreshold: 30
      periodSeconds: 10
  auth:
    username: elastic
    password: parrot

rabbitmq:
  replicaCount: 1
  image:
    repository: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-rabbitm
    tag: "3.9.13-debian-10-r26"
    pullPolicy: Always
  imagePullSecrets:
    - name: regsecret
  service:
    type: NodePort
    port: 5672
    nodePort: 30084
  resources:
    requests:
      cpu: 100m
      memory: 1200Mi
  probes:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 30
      periodSeconds: 10
    startup:
      failureThreshold: 30
      periodSeconds: 10
  auth:
    username: chatbot
    password: chatbot
  plugins: "rabbitmq_management rabbitmq_stomp rabbitmq_web_stomp"
#  plugins:
#    - rabbitmq_management
#    - rabbitmq_stomp
#    - rabbitmq_web_stomp

redis:
  replicaCount: 1
  image:
    repository: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-redis
    tag: "7.0.1-debian-11-r3"
    pullPolicy: Always
  imagePullSecrets:
    - name: regsecret
  service:
    type: NodePort
    port: 6379
    nodePort: 30085
  resources:
    requests:
      cpu: 100m
      memory: 1200Mi
  probes:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 30
      periodSeconds: 10
    startup:
      failureThreshold: 30
      periodSeconds: 10
  auth:
    password: chatbot
