replicaCount: 1

image:
  repository: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-rabbitmq
  tag: 3.9.13-debian-10-r26
  pullPolicy: Always

service:
  type: NodePort
  port: 5672
  nodePort: 30083

resources:
  requests:
    cpu: 100m
    memory: 1200Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  path: /

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  path: /

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  port: 5672

imagePullSecrets:
  - name: regsecret

rabbitmqPlugins:
  - rabbitmq_management
  - rabbitmq_stomp
  - rabbitmq_web_stomp

rabbitmqCredentials:
  username: elastic
  password: elastic
