# startup Porbe 적용
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nls-redis-deployment
  namespace: test
  labels:
    app: nls-redis
  annotations:
    kubernetes.io/change-cause: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-redis:7.0.1-debian-11-r3
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nls-redis
  template:
    metadata:
      labels:
        app: nls-redis
    spec:
      containers:
        - name: redis
          image: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-redis:7.0.1-debian-11-r3
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 1200Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /
              port: 6379
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /
              port: 6379
          startupProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: regsecret
