apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  labels:
    app: {{ .Values.commonLabels.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.commonLabels.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.containerPorts.amqp }}
    targetPort: {{ .Values.containerPorts.amqp }}
    nodePort: {{ .Values.service.nodePorts.amqp }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
