apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nls-rabbitmq.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nls-rabbitmq.name" . }}
  annotations:
    kubernetes.io/change-cause: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "nls-rabbitmq.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nls-rabbitmq.name" . }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.port }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.port }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.startupProbe.port }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmqCredentials.username }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmqCredentials.password }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets[0].name }}
