apiVersion: v1
kind: Service
metadata:
  name: nls-elastic-svc
  namespace: test
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  labels:
    app: nls-elastic
spec:
  type: NodePort
  selector:
    app: nls-elastic
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30085
