apiVersion: apps/v1
kind: Deployment
metadata:
  name: nls-elastic-deployment
  namespace: test
  labels:
    app: nls-elastic
  annotations:
    kubernetes.io/change-cause: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-elasticsearch:7.10.2
spec:
  replicas: 3
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nls-elastic
  template:
    metadata:
      labels:
        app: nls-elastic
    spec:
      containers:
      - name: core
        image: seoulbigdata-registry.ncr.gov-ntruss.com/nls-docker-elasticsearch:7.10.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 1350Mi
      imagePullSecrets:
      - name: regsecret
