apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  labels:
    app: {{ .Values.commonLabels.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.commonLabels.app }}
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: {{ .Values.service.nodePorts.amqp }}
