apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
  labels:
    app: {{ .Values.commonLabels.app }}
  annotations:
    kubernetes.io/change-cause: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.commonLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.commonLabels.app }}
    spec:
      containers:
      - name: core
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPorts.amqp }}
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 1200Mi
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
           path: /
           port: {{ .Values.containerPorts.amqp }}
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            path: /
            port: {{ .Values.containerPorts.amqp }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.containerPorts.amqp }}
          failureThreshold: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets[0] }}
