apiVersion: apps/v1
kind: Deployment
metadata:
  name: nls-elasticsearch-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: nls-elastic
  annotations:
    kubernetes.io/change-cause: {{ .Values.image.repository }}:{{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nls-elastic
  template:
    metadata:
      labels:
        app: nls-elastic
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9200
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            - name: ELASTIC_USERNAME
              value: {{ .Values.auth.username }}
            - name: ELASTIC_PASSWORD
              value: {{ .Values.auth.password }}
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          startupProbe:
            tcpSocket:
              port: 9200
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets[0].name }}
