apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
  labels:
    app: {{ .Values.commonLabels.app }}
  annotations:
    kubernetes.io/change-cause: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.commonLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.commonLabels.app }}
    spec:
      containers:
      - name: core
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9200
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 1350Mi
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets[0] }}
