apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  name: nls-elasticsearch-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: nls-elastic
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9200
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: nls-elastic
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
