apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - name: elasticsearch
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        env:
        - name: ELASTIC_USERNAME
          value: {{ .Values.elasticsearch.auth.username }}
        - name: ELASTIC_PASSWORD
          value: {{ .Values.elasticsearch.auth.password }}
        resources:
          requests:
            cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
            memory: {{ .Values.elasticsearch.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: {{ .Values.elasticsearch.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.elasticsearch.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: {{ .Values.elasticsearch.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.elasticsearch.probes.readiness.periodSeconds }}
        startupProbe:
          httpGet:
            path: /
            port: 9200
          failureThreshold: {{ .Values.elasticsearch.probes.startup.failureThreshold }}
          periodSeconds: {{ .Values.elasticsearch.probes.startup.periodSeconds }}
