apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespaceOverride }}
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/description: '{{ .Values.ingress.description }}'
    alb.ingress.kubernetes.io/load-balancer-name: '{{ .Values.ingress.loadBalancerName }}'
    alb.ingress.kubernetes.io/load-balancer-size: '{{ .Values.ingress.loadBalancerSize }}'
    alb.ingress.kubernetes.io/actions.{{ .Values.ingress.actions.serviceName }}: >
      {"type":"targetGroup","targetGroup":{"targetGroups":[{"serviceName":"{{ .Values.ingress.actions.serviceName }}","servicePort":{{ .Values.ingress.actions.servicePort }},"weight":100}],"enableStickySession":true}}
  labels:
    app: {{ .Values.ingress.labels.app }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /bsp/mtv
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.actions.serviceName }}
            port:
              name: use-annotation
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.actions.serviceName }}
            port:
              name: use-annotation
