apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: 5672
      nodePort: {{ .Values.rabbitmq.service.nodePort }}
  selector:
    app: rabbitmq
