apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  name: nls-elasticsearch-service
  namespace: test
  labels:
    app: elasticsearch-docker
spec:
  type: NodePort
  selector:
    app: elasticsearch-docker
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30083
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
