apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  name: {{ include "elasticsearch.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "elasticsearch.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "elasticsearch.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
