apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /bsp
  name: web-portal-service
  namespace: prod
  labels:
    app: web-portal-tomcat
spec:
  type: NodePort
  selector:
    app: web-portal-tomcat
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
